# -*- coding: utf-8 -*-
"""ClimateGuardian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJ-0EVztidxfp5RoPMAsY8kuUmodZz0N

**Project Title:** ClimateGuardian AI – Climate Change Prediction and Analysis System

**Project Description:**
ClimateGuardian AI is an artificial intelligence-based system developed to support **SDG 13: Climate Action** by analyzing historical climate data and human activity indicators to understand and predict the impact of climate change. The system uses machine learning techniques to analyze environmental factors such as CO₂ emissions, methane emissions, nitrous oxide levels, energy consumption, population, and GDP to identify the major contributors to climate pollution.

The model predicts future pollution trends and climate risks for upcoming years, helping to estimate potential environmental impacts. It also analyzes which human activities contribute most to pollution and provides data-driven insights that can support policymakers and environmental organizations in developing effective climate mitigation strategies. The system further generates automated policy recommendations based on pollution levels and environmental indicators to encourage sustainable practices and reduce climate change risks.
"""

!pip install pandas numpy matplotlib seaborn scikit-learn torch transformers plotly shap

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

import torch
import torch.nn as nn

import plotly.express as px

temp_url = "https://raw.githubusercontent.com/datasets/global-temp/master/data/annual.csv"
co2_url = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"

temp = pd.read_csv(temp_url)
co2 = pd.read_csv(co2_url)

co2 = co2[[
    "year",
    "co2",
    "methane",
    "nitrous_oxide",
    "energy_per_capita",
    "population",
    "gdp"
]]

co2 = co2.groupby("year").mean().reset_index()

data = pd.merge(temp, co2, left_on="Year", right_on="year")

data = data.dropna()

data.head()

plt.figure(figsize=(10,6))

# Select only numeric columns
numeric_data = data.select_dtypes(include=['number'])

sns.heatmap(numeric_data.corr(), cmap="coolwarm", annot=True)

plt.title("Climate Variable Correlation")
plt.show()

features = [
    "co2",
    "methane",
    "nitrous_oxide",
    "energy_per_capita",
    "population",
    "gdp"
]

target = "Mean"

scaler = MinMaxScaler()

scaled = scaler.fit_transform(data[features + [target]])

def create_sequences(data, seq_len=10):

    X = []
    y = []

    for i in range(len(data)-seq_len):

        X.append(data[i:i+seq_len,:-1])
        y.append(data[i+seq_len,-1])

    return np.array(X), np.array(y)

X, y = create_sequences(scaled)

class ClimateModel(nn.Module):

    def __init__(self):

        super().__init__()

        self.lstm = nn.LSTM(
            input_size=6,
            hidden_size=64,
            batch_first=True
        )

        self.attention = nn.MultiheadAttention(
            embed_dim=64,
            num_heads=4
        )

        self.fc = nn.Linear(64,1)

    def forward(self,x):

        lstm_out,_ = self.lstm(x)

        lstm_out = lstm_out.permute(1,0,2)

        attn_out,_ = self.attention(
            lstm_out,
            lstm_out,
            lstm_out
        )

        out = self.fc(attn_out[-1])

        return out

model = ClimateModel()

criterion = nn.MSELoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

X_tensor = torch.tensor(X).float()
y_tensor = torch.tensor(y).float()

for epoch in range(200):

    optimizer.zero_grad()

    output = model(X_tensor)

    loss = criterion(output, y_tensor)

    loss.backward()

    optimizer.step()

    if epoch % 20 == 0:
        print("Epoch:",epoch,"Loss:",loss.item())

future = X_tensor[-1].unsqueeze(0)

prediction = model(future)

print("Future Temperature Change:", prediction.item())

def risk_score(temp):

    if temp > 2:
        return "EXTREME RISK"

    elif temp > 1.5:
        return "HIGH RISK"

    elif temp > 1:
        return "MODERATE RISK"

    else:
        return "LOW RISK"

print(risk_score(prediction.item()))

risk = pd.DataFrame({

    "country":[
        "India",
        "USA",
        "China",
        "Brazil",
        "Germany"
    ],

    "risk":[0.8,0.6,0.7,0.5,0.4]

})

fig = px.choropleth(
    risk,
    locations="country",
    locationmode="country names",
    color="risk",
    title="Global Climate Risk Map"
)

fig.show()

from transformers import pipeline

policy_ai = pipeline(
    "text-generation",
    model="gpt2"
)

def generate_policy(temp):

    prompt = f"""
    Global temperature increase is {temp}°C.
    Suggest climate mitigation strategies for governments.
    """

    result = policy_ai(
        prompt,
        max_length=120
    )

    return result[0]["generated_text"]

print(generate_policy(prediction.item()))

X_np = X_tensor.detach().numpy()

def predict_fn(data):

    data_tensor = torch.tensor(data).float()

    with torch.no_grad():
        output = model(data_tensor)

    return output.detach().numpy()

import shap

background = X_np[:100]

explainer = shap.Explainer(predict_fn, background)

import shap

X_np = X_tensor.detach().numpy()

seq_len = X_np.shape[1]
n_features = X_np.shape[2]

X_flat = X_np.reshape(X_np.shape[0], seq_len * n_features)

def predict_fn(data):

    data = data.reshape(data.shape[0], seq_len, n_features)

    data_tensor = torch.tensor(data).float()

    with torch.no_grad():
        preds = model(data_tensor)

    return preds.detach().numpy()

background = X_flat[:50]

explainer = shap.KernelExplainer(
    predict_fn,
    background
)

shap_values = explainer.shap_values(X_flat[:10])

shap.summary_plot(
    shap_values,
    X_flat[:10]
)

plt.figure(figsize=(10,6))

features = [
    "co2",
    "methane",
    "nitrous_oxide",
    "energy_per_capita",
    "population",
    "gdp"
]

target = "Mean"

importance = data[features].corrwith(data[target])

importance.sort_values().plot(
    kind="barh",
    color="red"
)

plt.title("Pollution Contribution by Factor")
plt.xlabel("Impact on Temperature")
plt.show()

print(co2.columns)

co2_url = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"

co2 = pd.read_csv(co2_url)

print(co2.columns)

country_pollution = (
    co2[co2["iso_code"].notna()]      # remove continents like Asia, World
    .groupby("country")["co2"]
    .mean()
    .sort_values(ascending=False)
)

top_polluters = country_pollution.head(10)

plt.figure(figsize=(10,6))

top_polluters.plot(kind="bar", color="darkred")

plt.title("Top 10 CO2 Polluting Countries")
plt.ylabel("Average CO2 Emissions")
plt.xlabel("Country")

plt.show()

import plotly.express as px

map_data = co2.groupby("country")["co2"].mean().reset_index()

fig = px.choropleth(
    map_data,
    locations="country",
    locationmode="country names",
    color="co2",
    title="Global CO2 Pollution Map"
)

fig.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

features = [
    "methane",
    "nitrous_oxide",
    "energy_per_capita",
    "population",
    "gdp"
]

target = "co2"

df = co2[features + ["year", target]].dropna()

X = df[features + ["year"]]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model_pollution = LinearRegression()

model_pollution.fit(X_train, y_train)

pred = model_pollution.predict(X_test)

future_years = np.arange(2030,2051)

future_data = pd.DataFrame({
    "year":future_years,
    "methane":df["methane"].mean(),
    "nitrous_oxide":df["nitrous_oxide"].mean(),
    "energy_per_capita":df["energy_per_capita"].mean(),
    "population":df["population"].mean(),
    "gdp":df["gdp"].mean()
})

future_predictions = model_pollution.predict(
    future_data[features + ["year"]]
)

future_data["predicted_co2"] = future_predictions

future_data.head()

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

plt.plot(
    future_data["year"],
    future_data["predicted_co2"],
    marker="o"
)

plt.title("Predicted CO2 Emissions (2030–2050)")
plt.xlabel("Year")
plt.ylabel("Predicted CO2")

plt.show()

pollution_factors = df[features].corrwith(df["co2"])

pollution_factors.sort_values().plot(
    kind="barh",
    figsize=(10,6),
    color="red"
)

plt.title("Human Activities Causing Pollution")
plt.xlabel("Impact on CO2 Emissions")

plt.show()

def generate_policy(co2, methane, energy):

    policies = []

    if co2 > df["co2"].mean():
        policies.append(
            "Implement carbon tax and reduce fossil fuel use"
        )

    if methane > df["methane"].mean():
        policies.append(
            "Improve agricultural methane management"
        )

    if energy > df["energy_per_capita"].mean():
        policies.append(
            "Increase renewable energy adoption"
        )

    if len(policies) == 0:
        policies.append(
            "Maintain sustainable environmental policies"
        )

    return policies

"""ex"""

generate_policy(
    co2=12,
    methane=3,
    energy=50000
)

def climate_risk(predicted_co2):

    if predicted_co2 > 15:
        return "EXTREME RISK"

    elif predicted_co2 > 10:
        return "HIGH RISK"

    elif predicted_co2 > 5:
        return "MODERATE RISK"

    else:
        return "LOW RISK"

"""example"""

climate_risk(12)